version: '3'
name: "scamazon"

networks:
  my_network:
    driver: bridge

volumes:
  mongo-product-service-data:
  mongo-user-service-data:
  mongo-order-service-data:
  


services:

  frontend-service:
    image: svenpaj/frontend-service:1.0.0
    networks:
      - my_network
    ports:
      - "4004:4004"
    
      
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3005:3000
    networks:
      - my_network

  product-catalog-service:
    image: svenpaj/product-service:1.0.0
    networks:
      - my_network
    ports:
      - "4005:4005"
    depends_on:
      mongo-1:
        condition: service_healthy

  mongo-1:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-product-service-data:/data/db
      - ./init/init-mongo-products.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'mongo.runCommand("ping").ok' | mongosh mongo-1:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 200s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: allProducts

  mongo-express-1:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    networks:
      - my_network
    depends_on:
      mongo-1:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-1:27017/

  user-management-service:
    image: svenpaj/user-service:1.0.0
    networks:
      - my_network
    ports:
      - "4006:4006"
    depends_on:
      mongo-2:
        condition: service_healthy


  mongo-2:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-user-service-data:/data/db
      - ./init/init-mongo-users.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'mongo.runCommand("ping").ok' | mongosh mongo-2:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 200s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: allUsers

  mongo-express-2:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    networks:
      - my_network
    depends_on:
      mongo-2:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-2:27017/

  order-processing-service:
    image: svenpaj/order-service:1.0.0
    networks:
      - my_network
    ports:
      - "4007:4007"
    depends_on:
      mongo-3:
        condition: service_healthy


  mongo-3:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-order-service-data:/data/db
      - ./init/init-mongo-orders.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'mongo.runCommand("ping").ok' | mongosh mongo-3:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 200s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: allOrders

  mongo-express-3:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    networks:
      - my_network
    depends_on:
      mongo-3:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-3:27017/