version: '3'
name: "scamazon"

networks:
  my_network:
    driver: bridge

volumes:
  mongo-data-home-page-service:
  mongo-data-order-processing-service:
  mongo-produkt-catalog-service:


services:

  home-page-service:
    build: github.com/DevOps22-Grupp1/home-page-service#prometheus-fix:backend
    networks:
      - my_network
    ports:
      - "5002:5002"
    depends_on:
      mongo-home-page-service:
        condition: service_healthy

  prometheus-home-page-service:
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  mongo-home-page-service:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-data-home-page-service:/data/db
    healthcheck:
      test: echo 'mongo-home-page-service.runCommand("ping").ok' | mongosh mongo-home-page-service:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express-home-page-service:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - my_network
    depends_on:
      mongo-home-page-service:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-home-page-service:27017/

  order-processing-service:
    build: github.com/DevOps22-Grupp1/order-processing-service/#project-merge:backend
    networks:
      - my_network
    depends_on:
      mongo-order-processing-service:
        condition: service_healthy

  prometheus-order-processing-service:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  mongo-order-processing-service:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-data-order-processing-service:/data/db
    healthcheck:
      test: echo 'mongo-order-processing-service.runCommand("ping").ok' | mongosh mongo-order-processing-service:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express-order-processing-service:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    networks:
      - my_network
    depends_on:
      mongo-order-processing-service:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-order-processing-service:27017/

  produkt-catalog-service:
    build: github.com/DevOps22-Grupp1/produkt-catalog-service#project-merge:backend
    networks:
      - my_network
    depends_on:
      mongo-produkt-catalog-service:
        condition: service_healthy

  prometheus-produkt-catalog-service:
    image: prom/prometheus:latest
    ports:
      - "9094:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  mongo-produkt-catalog-service:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-data-produkt-catalog-service:/data/db
    healthcheck:
      test: echo 'mongo-produkt-catalog-service.runCommand("ping").ok' | mongosh mongo-produkt-catalog-service:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express-produkt-catalog-service:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    networks:
      - my_network
    depends_on:
      mongo-produkt-catalog-service:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-produkt-catalog-service:27017/

  user-management-service:
    build: ./backend
    networks:
      - my_network
    ports:
      - "5000:5002"
    depends_on:
      mongo-user-management-service:
        condition: service_healthy

  prometheus-user-management-service:
    image: prom/prometheus:latest
    ports:
      - "9099:9090"
    networks:
      - my_network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml

  mongo-user-management-service:
    image: mongo
    restart: always
    networks:
      - my_network
    volumes:
      - ./mongo-data:/data/db
      - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'mongo.runCommand("ping").ok' | mongosh mongo-user-management-service:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: testdb

  mongo-express-user-management-service:
    image: mongo-express
    restart: always
    ports:
      - 8087:8081
    networks:
      - my_network
    depends_on:
      mongo-user-management-service:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-user-management-service:27017/
