apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-adminer
  namespace: mysql
  labels:
    app: mysql-adminer
spec:
  selector:
    matchLabels:
      app: mysql-adminer
  template:
    metadata:
      labels:
        app: mysql-adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4.8.1
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DESIGN
              value: "pappu687"
            - name: ADMINER_DEFAULT_DB_DRIVER	
              value: "mysql"
            - name: ADMINER_DEFAULT_DB_HOST
              value: "mysql-service"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-adminer-svc
  namespace: mysql
spec:
  selector:
    app: mysql-adminer
  type: NodePort  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30011
