apiVersion: gemini.fairwinds.com/v1
kind: SnapshotGroup
metadata:
  name: mysql-backup
  namespace: mysql
spec:
  persistentVolumeClaim:
    claimName: mysql-pv-claim
  schedule:
    - every: "10 minutes"
      keep: 3
  template:
    spec:
      volumeSnapshotClassName: csi-hostpath-snapclass