
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: mysql
spec:
  selector:
    app: wordpress
  type: NodePort  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: mysql
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
      containers:
        - name: wordpress
          image: wordpress:6.3.2-apache
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: wordpress-db
