apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata: 
  name: "mongodb-pvc"
  labels: 
    app: "mongo-db"
spec: 
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
  storageClassName: gp2

---
apiVersion: "v1"
kind: "Service"
metadata: 
  name: "mongo-db"
  labels: 
    app: "mongo-db"
spec: 
  ports: 
    - 
      name: "mongodb"
      port: 27017
      targetPort: 27017
  clusterIP: "None"
  selector: 
    app: "mongo-db"
