apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  # storageClassName: csi-hostpath-snapclass
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
     storage: 5Gi
  storageClassName: csi-hostpath-sc



#      # example-pvc.yaml $ kubectl -n default  exec -it  mongodb-deployment-565f959dff-g2sb7  -- bash 
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: csi-pvc
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: csi-hostpath-sc