apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-csi-volume-snapshot
spec:
  volumeSnapshotClassName: volume-snapshot-class #change it with your volume snapshot class name
  source:
    persistentVolumeClaimName: mongo-pv-claim # change it with target pvc name
