apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup
spec:
  # storageClassName: csi-hostpath-snapclass
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
     storage: 2Gi
  storageClassName: hostpath