apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-restore
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 1800
  ttlSecondsAfterFinished: 50
  backoffLimit: 6   
  template:         
    metadata:
      name: pi
    spec:
      volumes:
        - name: mongodump-volume
          persistentVolumeClaim:
            claimName: mongo-dump-pv-claim
      containers:
      - name: mongodump-restore
        image: passwordnotsafe/mongo-backup
        imagePullPolicy: Always
        env:
          - name: FILE
            value: "data_handling_12"
          - name: MONGOD_HOST
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
          - name: MONGOD_PORT
            value: "27017"
          - name: MONGODB_URI
            value: "mongodb://"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
        volumeMounts:
                - mountPath: "/mongodump"
                  name: mongodump-volume
        command: ['sh', '-c',"./restore.sh"]
      restartPolicy: OnFailure
              
      