name: "scamazon"

on:
  push:
    branches:
      - 6-cypress-testing-workflows

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.8
        command: ["dind"]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and start services
        run: |
          docker build -t passwordnotsafe/home-page-service -f Dockerfile_home-page-service .
          docker build -t passwordnotsafe/order-processing-service -f Dockerfile_order-processing-service .
          docker build -t passwordnotsafe/produkt-catalog-service -f Dockerfile_produkt-catalog-service .
          docker build -t passwordnotsafe/user-management-service -f Dockerfile_user-management-service .
          
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be healthy
        run: docker-compose -f docker-compose.yml exec -T home-page-service ./wait-for.sh order-processing-service:4007 produkt-catalog-service:4005 user-management-service:4006

      - name: Run Cypress tests
        run: |
          # Install Cypress dependencies if needed
          npm install

          # Run Cypress tests
          npx cypress run

      - name: Stop services
        run: docker-compose -f docker-compose.yml down
