name: CI

on:
  push:
    branches:
      - 6-cypress-testing-workflows

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      home-page-service:
        image: passwordnotsafe/home-page-service

      order-processing-service:
        image: passwordnotsafe/order-processing-service:master

      mongo-order-processing-service:
        image: mongo
        options: --health-cmd="health-check-command-for-service3" --health-interval=10s --health-timeout=5s --health-retries=3

      mongo-express-order-processing-service:
        image: mongo-express

      product-catalog-service:
        image: passwordnotsafe/produkt-catalog-service:master

      mongo-product-catalog-service:
        image: mongo
        options: --health-cmd="health-check-command-for-service3" --health-interval=10s --health-timeout=5s --health-retries=3

      mongo-express-product-catalog-service:
        image: mongo-express

      user-management-service:
        image: passwordnotsafe/user-management-service

      mongo-user-management-service:
        image: mongo
        options: --health-cmd="health-check-command-for-service3" --health-interval=10s --health-timeout=5s --health-retries=3

      mongo-express-user-management-service:
        image: mongo-express

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose -f ../docker-compose.yml up -d

      - name: Run Cypress tests
        run: |
          # Install Cypress dependencies if needed
          npm install

          # Run Cypress tests
          npx cypress run

      - name: Stop Docker Compose
        run: docker-compose -f ../docker-compose.yml down
